### ISSUE TITLE
Core codes for the sandwich weight sharing 

### ISSUE THREAD

**Issue by qianlou** [machelreid/subformer#1]
Dear Subformer authors,

Thanks for sharing your codes on the interesting subformer work! I am eager to reproduce your experiments on sandwich weight sharing. But I am a little confused about finding your core codes from the fairseq templete. Is it mainly in the fairseq/modules/subformer_layer.py? Could you kindly introduce your core codes on weight sharing? Thanks very much!

Bests,
Qian

**Comment by machelreid** [comment]
Hi Qian!

The sandwich-style parameter sharing is implemented in [fairseq/models/transformer.py](https://github.com/machelreid/subformer/blob/master/fairseq/models/transformer.py).

Let me know if that helps!

Best,
Machel

**Comment by qianlou** [comment]
Thanks for your feedback. Very helpful!
