### ISSUE TITLE
How to reproduce the result of abstractive summarization?

### ISSUE THREAD

**Issue by minjieyuan** [machelreid/subformer#2]
Dear Subformer authors,
Hi! Thanks for sharing your codes! I want to reproduce the results of abstractive summarization, but I'm confused about how to set the training parameters. I use the same scripts of [Training](https://github.com/machelreid/subformer#training) but the result is bad. Could you kindly provide the scripts for summarization task? Thank you very much!

**Comment by machelreid** [comment]
Hi @minjieyuan!

I've improved the readme with the instructions for summarization. Let me know what you think!

Best,
Machel

**Comment by minjieyuan** [comment]
@machelreid Thank you!

**Comment by minjieyuan** [comment]
> Hi @minjieyuan!
> 
> I've improved the readme with the instructions for summarization. Let me know what you think!
> 
> Best,
> Machel

@machelreid  Sorry, I still have some errors. The error is as follows.

  File "/path/to/subformer/fairseq/modules/subformer_layer.py", line 456, in forward
    query=x * self.hadamard_encoder_attn[0],
RuntimeError: The size of tensor a (512) must match the size of tensor b (1024) at non-singleton dimension 2

Could you help please?

**Comment by machelreid** [comment]
Should be fixed!
